export const SITE = {
  website: "https://haorio-lab.hozeronoh.workers.dev/",
  author: "Haorio",
  profile: "https://github.com/Haorio-Lab",
  desc: "기술, 자동화, 그리고 일상을 기록하는 실험실.",
  title: "Haorio Lab",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/Haorio-Lab/haorio-lab/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "ko",
  timezone: "Europe/Berlin",
} as const;
